apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: shop
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus.shop.svc.cluster.local:9090
        isDefault: true
        jsonData:
          exemplarTraceIdDestinations:
            - name: traceID
              datasourceUid: tempo

      - name: Loki
        type: loki
        uid: loki
        url: http://loki.shop.svc.cluster.local:3100
        jsonData:
          derivedFields:
            - name: TraceID
              matcherRegex: '"traceId":"(\w+)"'
              url: "$${__value.raw}"
              datasourceUid: tempo
              urlDisplayLabel: "View in Tempo"
            - name: TraceIDMetadata
              matcherType: label
              matcherRegex: trace[_]?id
              url: "$${__value.raw}"
              datasourceUid: tempo
              urlDisplayLabel: "View in Tempo"

      - name: Pyroscope
        type: grafana-pyroscope-datasource
        uid: pyroscope
        url: http://pyroscope.shop.svc.cluster.local:4040

      - name: Tempo
        type: tempo
        uid: tempo
        url: http://tempo.shop.svc.cluster.local:3200
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            spanStartTimeShift: "-1m"
            spanEndTimeShift: "1m"
            filterByTraceID: true
            filterBySpanID: false
          serviceMap:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true
          tracesToProfilesV2:
            datasourceUid: pyroscope
            profileTypeId: process_cpu:cpu:nanoseconds:cpu:nanoseconds
            customQuery: true
            query: "$${__span.tags[\"service.name\"]}"
          search:
            hide: false
          lokiSearch:
            datasourceUid: loki
