global:
  scrape_interval: 15s
scrape_configs:
  - job_name: shop-apps
    static_configs:
      - targets:
          - auth-server:8081
          - api-gateway:8081
          - buyer-bff:8081
          - seller-bff:8081
          - profile-service:8081
          - promotion-service:8081
          - wallet-service:8081
          - marketplace-service:8081
          - buyer-portal:8081
          - seller-portal:8081
